### ISSUE TITLE
import stringを使うと簡単

### ISSUE THREAD

**Issue by c0a2110056** [c0a21142/ProjExD#4]
https://github.com/c0a21142/ProjExD/blob/88ee5965327e9fab29688d0403bdddd5062e1de9/ex02/alphabet.py#L2
アルファベット大文字でを全部だすなら、string.ascii_uppercaseを使うと簡単よ

**Comment by c0a21142** [comment]
Unicodeのchrを使ってfor文で直したので参考としてコメントアウトして保存します。
