### ISSUE TITLE
#ffffffや#000000

### ISSUE THREAD

**Issue by c0a2110056** [c0a21142/ProjExD#6]
https://github.com/c0a21142/ProjExD/blob/da3f01068a58ae94928382ac5776d5e7dddb3a21/ex02_Re/calk.py#L43
こうやってもできるんだと初めて知りました。
私は"white"や"black"でやっていました。

**Comment by c0a21142** [comment]
普通に色を入力しても反映されることをコメントで知りました。
文字コードのみだと分かりにくいのでコメントアウトで文字コードの色を記入しました。
